### ISSUE TITLE
What if i need to submit my app's source code ?

### ISSUE THREAD

**Issue by flazouh** [wdzeng/firefox-addon#5]
<img width="499" alt="Screenshot 2024-08-12 at 00 29 53" src="https://github.com/user-attachments/assets/116c5fd7-532e-45f5-b195-2568f0bed777">

**Comment by flazouh** [comment]
is this supported by the amo api ?

**Comment by wdzeng** [comment]
> is this supported by the amo api ?

Yes, but my action does not have this feature. I am working on this.

**Comment by wdzeng** [comment]
Hi @flazouh, did you want to try `v1.1.0-alpha.1` that supports upload source code file?

```yaml
steps:
  - uses: wdzeng/firefox-addon@v1.1.0-alpha.1
    with:
      addon-guid: your-addon's-guid
      xpi-path: your-addon.zip
      self-hosted: false
      jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
      jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
      source-file-path: your-source-file.zip
```
